In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/classify-fruits/sample_submission.csv
/kaggle/input/classify-fruits/fruits_test.csv
/kaggle/input/classify-fruits/fruits_train.csv


In [2]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
fruits_train = pd.read_csv("/kaggle/input/classify-fruits/fruits_train.csv")
fruits_test = pd.read_csv("/kaggle/input/classify-fruits/fruits_test.csv")

In [3]:
x_train = fruits_train.to_numpy()
x_train = x_train[:,1:4]
x_test = fruits_test.to_numpy()
x_test = x_test[:,1:4]
y_train = fruits_train.to_numpy()
y_train = y_train[:,4]

In [4]:
x_train

array([[160. ,   7.1,   7.6],
       [194. ,   7.2,  10.3],
       [154. ,   7.2,   7.2],
       [154. ,   7. ,   7.1],
       [162. ,   7.4,   7.2],
       [164. ,   7.2,   7. ],
       [154. ,   7.1,   7.5],
       [116. ,   6.1,   8.5],
       [170. ,   7.6,   7.9],
       [116. ,   5.9,   8.1],
       [144. ,   6.8,   7.4],
       [160. ,   7.5,   7.5],
       [166. ,   6.9,   7.3],
       [142. ,   7.6,   7.8],
       [156. ,   7.4,   7.4],
       [116. ,   6. ,   7.5],
       [356. ,   9.2,   9.2],
       [152. ,   6.5,   8.5],
       [164. ,   7.3,   7.7],
       [162. ,   7.5,   7.1],
       [158. ,   7.1,   7.5],
       [140. ,   7.3,   7.1],
       [186. ,   7.2,   9.2],
       [174. ,   7.3,  10.1],
       [180. ,   8. ,   6.8],
       [168. ,   7.5,   7.6],
       [216. ,   7.3,  10.2],
       [160. ,   7. ,   7.4],
       [172. ,   7.1,   7.6],
       [140. ,   6.7,   7.1],
       [180. ,   7.6,   8.2],
       [362. ,   9.6,   9.2],
       [342. ,   9. ,   9.4],
       [15

In [5]:
x_test

array([[118. ,   6.1,   8.1],
       [158. ,   7.2,   7.8],
       [120. ,   6. ,   8.4],
       [210. ,   7.8,   8. ],
       [156. ,   7.6,   7.5],
       [176. ,   7.4,   7.2],
       [154. ,   7.3,   7.3],
       [196. ,   7.3,   9.7],
       [130. ,   6. ,   8.2],
       [150. ,   7.1,   7.9],
       [172. ,   7.4,   7. ],
       [156. ,   7.7,   7.1],
       [190. ,   7.5,   8.1],
       [204. ,   7.5,   9.2]])

In [6]:
y_train

array([2., 3., 2., 1., 1., 2., 2., 3., 1., 3., 2., 1., 1., 2., 1., 3., 2.,
       3., 1., 1., 2., 1., 3., 3., 1., 1., 3., 2., 1., 2., 2., 2., 2., 1.,
       3., 3., 1., 1., 3., 3.])

In [7]:
sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

In [8]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x_train, y_train)
output_data = knn.predict(x_test)
print(output_data)

[3. 2. 3. 1. 1. 1. 1. 3. 3. 2. 1. 1. 1. 3.]


In [9]:
modify_data = pd.DataFrame({'ID': fruits_test['Id'], 'Category': np.array(output_data)})

In [10]:
modify_data.to_csv('output_data.csv')